import pytz

APP_TITLE = "Stock Insights"
APP_ICON = "📈"
IST = pytz.timezone("Asia/Kolkata")

NIFTY_50_SYMBOLS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "KOTAKBANK.NS", "LT.NS", "AXISBANK.NS",
    "BAJFINANCE.NS", "ASIANPAINT.NS", "MARUTI.NS", "WIPRO.NS", "HCLTECH.NS",
    "ULTRACEMCO.NS", "TITAN.NS", "SUNPHARMA.NS", "POWERGRID.NS", "NTPC.NS",
    "BHARTIARTL.NS", "SBIN.NS", "ONGC.NS", "TATAMOTORS.NS", "TATASTEEL.NS",
    "TECHM.NS", "DIVISLAB.NS", "CIPLA.NS", "DRREDDY.NS", "ADANIPORTS.NS",
    "BAJAJFINSV.NS", "BPCL.NS", "BRITANNIA.NS", "COALINDIA.NS", "EICHERMOT.NS",
    "GRASIM.NS", "HDFCLIFE.NS", "HEROMOTOCO.NS", "HINDALCO.NS", "INDUSINDBK.NS",
    "JSWSTEEL.NS", "M&M.NS", "NESTLEIND.NS", "SBILIFE.NS", "SHREECEM.NS",
    "TATACONSUM.NS", "TRENT.NS", "UPL.NS", "VEDL.NS", "WIPRO.NS",
]

INDICES = {
    "NIFTY 50": "^NSEI",
    "SENSEX": "^BSESN",
    "NIFTY Bank": "^NSEBANK",
    "NIFTY IT": "^CNXIT",
}

PREDICTION_HORIZONS = {
    "1 Week": 7,
    "1 Month": 30,
    "3 Months": 90,
    "6 Months": 180,
}

CACHE_TTL_MINUTES = 15
HISTORY_DAYS_DEFAULT = 365
HISTORY_DAYS_PREDICTION = 730

NSE_OPEN_HOUR, NSE_OPEN_MIN = 9, 15
NSE_CLOSE_HOUR, NSE_CLOSE_MIN = 15, 30
